spring:
  application:
    name: lifeline-backend
  datasource:
    url: jdbc:h2:file:./data/lifeline;MODE=MySQL # 로컬 재시작 후에도 회원/미션 데이터 유지
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # 로컬 개발 중 서버 재시작 시 기존 데이터 삭제 방지
    show-sql: true     # 콘솔에 쿼리문 보여주기
    properties:
      hibernate:
        format_sql: true # 쿼리문을 예쁘게 정렬해서 보여주기
  h2:
    console:
      enabled: true    # 브라우저에서 DB 안을 들여다볼 수 있게 해줌 (localhost:8080/h2-console)
      path: /h2-console



jwt:
  secret-key: aG90dGEtbGlmZWxpbmUtY2Fwc3RvbmUtcHJvamVjdC1zZWNyZXQta2V5LW11c3QtYmUtdmVyeS1sb25n # 이거 나중에 바꿀거임. 임시로 이래해놓음
  access-token-expiration: 3600000 # 1시간 (밀리초)
  refresh-token-expiration: 1209600000 # 14일 (밀리초)
